// Code generated by go:generate; DO NOT EDIT.

// Generated with command: go generate
// (from the project root)

package modules

import (
	_ "github.com/GoMudEngine/GoMud/modules/achievements"
	_ "github.com/GoMudEngine/GoMud/modules/aicompanion"
	_ "github.com/GoMudEngine/GoMud/modules/auctions"
	_ "github.com/GoMudEngine/GoMud/modules/baubles"
	_ "github.com/GoMudEngine/GoMud/modules/cleanup"
	_ "github.com/GoMudEngine/GoMud/modules/follow"
	_ "github.com/GoMudEngine/GoMud/modules/gmcp"
	_ "github.com/GoMudEngine/GoMud/modules/leaderboards"
	_ "github.com/GoMudEngine/GoMud/modules/lookdetail"
	_ "github.com/GoMudEngine/GoMud/modules/npcidle"
	_ "github.com/GoMudEngine/GoMud/modules/playtest"
	_ "github.com/GoMudEngine/GoMud/modules/rifts"
	_ "github.com/GoMudEngine/GoMud/modules/roomlife"
	_ "github.com/GoMudEngine/GoMud/modules/time"
	_ "github.com/GoMudEngine/GoMud/modules/weather"
	_ "github.com/GoMudEngine/GoMud/modules/webhelp"
)
